### ISSUE TITLE
Subdividing file doesn't work?

### ISSUE THREAD

**Issue by Avephax** [MediosZ/obsidian-subdivider#8]
Either I'm doing something wrong or I don't know why this isn't doing anything.

![Obsidian_Gde9wACrY2](https://github.com/user-attachments/assets/21782c05-f4d6-4c71-9492-28437cef6a80)

**Comment by MediosZ** [comment]
Hi, there are some checks you can do first.
- Does your file contain any Header 1? Since only Header 1 will be converted to new files during a single pass.
- Is there any error reported? You can check this by inspecting the developer console(Ctrl+Shift+i).

Otherwise, maybe you can share the outline of your file to help me identify the problem.

**Comment by Avephax** [comment]
Got it! Thanks.
